Author := "SiakHooi"
packageVersion := "1.1.2"
PackageName := "Semvery"
packageUrl := "https://github.com/siakhooi/semvery/releases/download/" + packageVersion + "/" + PackageName + "-" + packageVersion + "-windows-x64.zip"

manifestsPath := "manifests/s/" + Author + "/" + PackageName + "/" + packageVersion
validate:
    winget.exe validate --manifest "{{ manifestsPath }}"

test:
    winget.exe install --manifest "{{ manifestsPath }}"

pr_title := Author + "." + PackageName + " " + packageVersion
gh_token := ""
submit:
    wingetcreate.exe submit --prtitle "{{ pr_title }}" --token "{{ gh_token }}" "{{ manifestsPath }}"

# 1.1.1 https://github.com/microsoft/winget-pkgs/pull/382422
# 1.1.2 https://github.com/microsoft/winget-pkgs/pull/387967
