Author := "SiakHooi"
packageVersion := "1.1.1"
PackageName := "Json2Table"
packageUrl := "https://github.com/" + Author + "/" + PackageName + "/releases/download/v" + packageVersion + "/" + PackageName + "_" + packageVersion + "_Windows_x86_64.zip"

manifestsPath := "manifests/s/" + Author + "/" + PackageName + "/" + packageVersion
validate:
    winget.exe validate --manifest "{{ manifestsPath }}"

test:
    winget.exe install --verbose --log test.log --manifest "{{ manifestsPath }}"

pr_title := Author + "." + PackageName + " " + packageVersion
gh_token := ""
submit:
    wingetcreate.exe submit --prtitle "{{ pr_title }}" --token "{{ gh_token }}" "{{ manifestsPath }}"

# https://github.com/microsoft/winget-pkgs/pull/381711
