# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SiakHooi.FiboPlanner
PackageVersion: 0.7.0
InstallerLocale: en-US
InstallerType: zip
ReleaseDate: 2026-05-01

UpgradeBehavior: install
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: fibo-planner.exe
  PortableCommandAlias: fibo-planner

Commands:
- fibo-planner
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/siakhooi/fibo-planner/releases/download/0.7.0/fibo-planner_0.7.0_Windows_x86_64.zip
  InstallerSha256: f90cce495ef06379b333edaf11be7dd7e111e9a09c7a1f11f7f36a1f87d1d002

- Architecture: arm64
  InstallerUrl: https://github.com/siakhooi/fibo-planner/releases/download/0.7.0/fibo-planner_0.7.0_Windows_arm64.zip
  InstallerSha256: 9b479bbd128a88a1ba0590e9bc1b319fd6f26c9969824ce0fe967dd78174ccc3

ManifestType: installer
ManifestVersion: 1.12.0
